(import (except (rnrs) string-hash string-ci-hash)
        (util)
        (_srfi :1)
        (_srfi :69)
        (sym)
        (pi abstract)
        (util)
        (testing)
        (church readable-scheme))

(normalize-names (test-expr))
;; (define (f a b . z)
;;   z)

;; (define (f x)
;;   (let*-values ([(x y z) (apply values '(a b c))])
;;     (list x y z)))